DROP TABLE DEPARTMENTS;
DROP TABLE USERS;
DROP TABLE EMPLOYERS;
DROP TABLE USERS_EMPLOYERS;
DROP TABLE INTERESTS;
DROP TABLE USERS_INTERESTS;
DROP TABLE PUBLICATIONS;
DROP TABLE USERS_PUBLICATIONS;
DROP TABLE SKILLS;
DROP TABLE USERS_SKILLS;
DROP TABLE UNIVERSITIES;
DROP TABLE USERS_UNIVERSITIES;

CREATE TABLE DEPARTMENTS
(
	DEP_ID		INT					NOT NULL AUTO_INCREMENT,
	NAME				VARCHAR(255)		NOT NULL,
	PRIMARY KEY (DEP_ID)
);

CREATE TABLE USERS 
(
		USER_ID			INT					NOT NULL AUTO_INCREMENT,
		USERNAME		VARCHAR(255)		NOT NULL UNIQUE,
		PASSWORD		VARCHAR(255)		NOT NULL,
		FNAME			VARCHAR(40)			NOT NULL,
		LNAME			VARCHAR(40)			NOT NULL,
		TITLE			VARCHAR(40),
		ACC_CREATED		DATETIME			NOT NULL,
		DEP_ID			INT					NOT NULL,
		HOMETOWN		VARCHAR(255),
		PHONE_NUM		VARCHAR(12),
		EMAIL			VARCHAR(255)		NOT NULL,
		BIO				VARCHAR(5000),
		RESUME			VARCHAR(255),
		PRIMARY KEY (USER_ID),
		FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENTS(DEP_ID)
);

CREATE TABLE EMPLOYERS
(
	EMP_ID			INT				NOT NULL AUTO_INCREMENT,
	NAME			VARCHAR(255)	NOT NULL,
	PRIMARY KEY (EMP_ID)
);

CREATE TABLE USERS_EMPLOYERS -- Interface table
(
	USER_ID			INT				NOT NULL,
	EMP_ID			INT				NOT NULL,
	JOB_TITLE		VARCHAR(255)	NOT NULL,
	EMP_ST_DATE		DATETIME,
	EMP_END_DATE	DATETIME,
	PRIMARY KEY (USER_ID, EMP_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYERS(EMP_ID)
);

CREATE TABLE INTERESTS 
(
	INT_ID			INT				NOT NULL AUTO_INCREMENT,
	NAME			VARCHAR(255)	NOT NULL,
	DESCRIPTION		VARCHAR(5000)	NOT NULL,
	PRIMARY KEY (INT_ID)
);

CREATE TABLE USERS_INTERESTS -- Interface table
(
	USER_ID			INT				NOT NULL,
	INT_ID			INT				NOT NULL,
	PRIMARY KEY (USER_ID, INT_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (INT_ID) REFERENCES INTERESTS(INT_ID)
);

CREATE TABLE PUBLICATIONS
(
	PUB_ID			INT				NOT NULL AUTO_INCREMENT,
	NAME			VARCHAR(255)	NOT NULL,
	YEAR			VARCHAR(4)		NOT NULL,
	LINK			VARCHAR(255)	NOT NULL,
	PRIMARY KEY (PUB_ID)
);

CREATE TABLE USERS_PUBLICATIONS -- Interface table
(
	USER_ID			INT				NOT NULL,
	PUB_ID			INT				NOT NULL,
	PRIMARY KEY(PUB_ID, USER_ID),
	FOREIGN KEY (PUB_ID) REFERENCES PUBLICATIONS(PUB_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE SKILLS
(
	SKILL_ID		INT				NOT NULL,
	NAME			VARCHAR(255)	NOT NULL,
	DESCRIPTION		VARCHAR(5000)	NOT NULL,
	PRIMARY KEY (SKILL_ID)
);

CREATE TABLE USERS_SKILLS -- Interface table
(
	USER_ID			INT				NOT NULL,
	SKILL_ID		INT				NOT NULL,
	PRIMARY KEY(SKILL_ID, USER_ID),
	FOREIGN KEY (SKILL_ID) REFERENCES SKILLS(SKILL_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE UNIVERSITIES
(
	UNIV_ID			INT				NOT NULL AUTO_INCREMENT,
	NAME			VARCHAR(255)	NOT NULL
);

CREATE TABLE USERS_UNIVERSITIES -- Interface table
(
	USER_ID			INT				NOT NULL,
	UNIV_ID			INT				NOT NULL,
	PRIMARY KEY(UNIV_ID, USER_ID),
	FOREIGN KEY (UNIV_ID) REFERENCES UNIVERSITIES(UNIV_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);